# Generated by Django 6.0.3 on 2026-03-22 13:24

import django.db.models.deletion
import enrollments.models.enrollments
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=9, validators=[enrollments.models.enrollments.validate_season], verbose_name='Stagione')),
                ('enrollment_date', models.DateField(verbose_name='Data Iscrizione')),
                ('guardian_signed', models.BooleanField(default=False, verbose_name='Firma Tutore')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='athletes.athlete', verbose_name='Atleta')),
            ],
            options={
                'verbose_name': 'Iscrizione',
                'verbose_name_plural': 'Iscrizioni',
                'ordering': ['-season', 'athlete'],
                'constraints': [models.UniqueConstraint(fields=('athlete', 'season'), name='unique_enrollment_per_season')],
            },
        ),
    ]
