# Generated by Django 6.0.3 on 2026-03-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_municipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin Tecnico'), ('admin', 'Amministratore'), ('operator', 'Operatore Amministrativo'), ('trainer', 'Allenatore'), ('member', 'Membro'), ('external', 'Collaboratore Esterno')], default='member', max_length=20, verbose_name='Ruolo'),
        ),
    ]
