# Generated by Django 6.0.3 on 2026-03-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='municipality',
            constraint=models.UniqueConstraint(fields=('name', 'province'), name='unique_municipality_per_province'),
        ),
    ]
