# Generated by Django 6.0.3 on 2026-03-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(max_length=3, unique=True, verbose_name='Codice ISO'),
        ),
    ]
