# Generated by Django 6.0.3 on 2026-03-26 14:47
#
# PRE-DEPLOY CHECK: This migration adds a UniqueConstraint on (name, province)
# to the Municipality table. It will fail if duplicate rows already exist.
# Before applying to a production database that contains Municipality data,
# verify there are no duplicates with:
#   SELECT name, province_id, COUNT(*) FROM geography_municipality
#   GROUP BY name, province_id HAVING COUNT(*) > 1;
# Data loaded exclusively via the import_geography command is safe (ISTAT data
# guarantees uniqueness of municipality names within a province).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='municipality',
            constraint=models.UniqueConstraint(fields=('name', 'province'), name='unique_municipality_per_province'),
        ),
    ]
