# Generated by Django 6.0.3 on 2026-03-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Cognome')),
                ('vat_number', models.CharField(max_length=11, unique=True, verbose_name='Partita IVA')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medico Sportivo',
                'verbose_name_plural': 'Medici Sportivi',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
